// clang-format off
/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode v1 to v2

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
*******************************************************************************/
#ifndef CO_OD_H_
#define CO_OD_H_

/*******************************************************************************
   CANopen DATA TYPES
*******************************************************************************/
   typedef bool_t       BOOLEAN;
   typedef uint8_t      UNSIGNED8;
   typedef uint16_t     UNSIGNED16;
   typedef uint32_t     UNSIGNED32;
   typedef uint64_t     UNSIGNED64;
   typedef int8_t       INTEGER8;
   typedef int16_t      INTEGER16;
   typedef int32_t      INTEGER32;
   typedef int64_t      INTEGER64;
   typedef float32_t    REAL32;
   typedef float64_t    REAL64;
   typedef char_t       VISIBLE_STRING;
   typedef oChar_t      OCTET_STRING;

   #ifdef DOMAIN
   #undef DOMAIN
   #endif

   typedef domain_t     DOMAIN;

#ifndef timeOfDay_t
    typedef union {
        unsigned long long ullValue;
        struct {
            unsigned long ms:28;
            unsigned reserved:4;
            unsigned days:16;
            unsigned reserved2:16;
        };
    }timeOfDay_t;
#endif

    typedef timeOfDay_t TIME_OF_DAY;
    typedef timeOfDay_t TIME_DIFFERENCE;

/*******************************************************************************
   FILE INFO:
      FileName:     solar_1.xdd
      FileVersion:  
      CreationTime: 2:06AM
      CreationDate: 06-01-2026
      CreatedBy:    
*******************************************************************************/


/*******************************************************************************
   DEVICE INFO:
      VendorName:     PSAS
      VendorNumber:   0
      ProductName:    Solar 1
      ProductNumber:  0
*******************************************************************************/


/*******************************************************************************
   FEATURES
*******************************************************************************/
  #define CO_NO_SYNC                     0   //Associated objects: 1005-1007
  #define CO_NO_EMERGENCY                1   //Associated objects: 1014, 1015
  #define CO_NO_TIME                     0   //Associated objects: 1012, 1013
  #define CO_NO_SDO_SERVER               1   //Associated objects: 1200-127F
  #define CO_NO_SDO_CLIENT               0   //Associated objects: 1280-12FF
  #define CO_NO_GFC                      0   //Associated objects: 1300
  #define CO_NO_SRDO                     0   //Associated objects: 1301-1341, 1381-13C0
  #define CO_NO_LSS_SERVER               0   //LSS Slave
  #define CO_NO_LSS_CLIENT               0   //LSS Master
  #define CO_NODE_GUARDING_SLAVE         0   //NG Slave
  #define CO_NODE_GUARDING_MASTER        0   //NG Master
  #define CO_NO_RPDO                     1   //Associated objects: 14xx, 16xx
  #define CO_NO_TPDO                     4   //Associated objects: 18xx, 1Axx
  #define CO_NO_NMT_MASTER               0
  #define CO_NO_TRACE                    0


/*******************************************************************************
   OBJECT DICTIONARY
*******************************************************************************/
   #define CO_OD_NoOfElements             38


/*******************************************************************************
   TYPE DEFINITIONS FOR RECORDS
*******************************************************************************/
/*1018      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED32     vendorID;
               UNSIGNED32     productCode;
               UNSIGNED32     revisionNumber;
               UNSIGNED32     serialNumber;
               }              OD_identity_t;
/*1200      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED32     COB_IDClientToServer;
               UNSIGNED32     COB_IDServerToClient;
               UNSIGNED8      node_id_od_sdo_client;
               }              OD_SDOServerParameter_t;
/*1400      */ typedef struct {
               UNSIGNED8      highestSubIndexSupported;
               UNSIGNED32     COB_IDUsedByRPDO;
               UNSIGNED8      transmissionType;
               }              OD_RPDOCommunicationParameter_t;
/*1600      */ typedef struct {
               UNSIGNED8      numberOfMappedApplicationObjectsInPDO;
               UNSIGNED32     applicationObject1;
               UNSIGNED32     applicationObject2;
               UNSIGNED32     applicationObject3;
               UNSIGNED32     applicationObject4;
               UNSIGNED32     applicationObject5;
               UNSIGNED32     applicationObject6;
               UNSIGNED32     applicationObject7;
               UNSIGNED32     applicationObject8;
               }              OD_RPDOMappingParameter_t;
/*1800      */ typedef struct {
               UNSIGNED8      highestSubIndexSupported;
               UNSIGNED32     COB_IDUsedByTPDO;
               UNSIGNED8      transmissionType;
               UNSIGNED16     inhibitTime;
               UNSIGNED8      compatibilityEntry;
               UNSIGNED16     eventTimer;
               UNSIGNED8      SYNCStartValue;
               }              OD_TPDOCommunicationParameter_t;
/*1A00      */ typedef struct {
               UNSIGNED8      numberOfMappedApplicationObjectsInPDO;
               UNSIGNED32     applicationObject1;
               UNSIGNED32     applicationObject2;
               UNSIGNED32     applicationObject3;
               UNSIGNED32     applicationObject4;
               UNSIGNED32     applicationObject5;
               UNSIGNED32     applicationObject6;
               UNSIGNED32     applicationObject7;
               UNSIGNED32     applicationObject8;
               }              OD_TPDOMappingParameter_t;
/*3002      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               VISIBLE_STRING hw_version[3];
               VISIBLE_STRING configs_version[32];
               VISIBLE_STRING fw_version[5];
               }              OD_versions_t;
/*3003      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED8      reset;
               UNSIGNED32     uptime;
               INTEGER8       temperature;
               UNSIGNED16     vrefint;
               }              OD_system_t;
/*4000      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED16     voltage;
               INTEGER16      current;
               UNSIGNED16     power;
               UNSIGNED16     voltage_avg;
               INTEGER16      current_avg;
               UNSIGNED16     power_avg;
               UNSIGNED16     voltage_max;
               INTEGER16      current_max;
               UNSIGNED16     power_max;
               UNSIGNED16     energy;
               }              OD_output_t;
/*4001      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER8       temperature;
               INTEGER8       temperature_min;
               INTEGER8       temperature_max;
               }              OD_cell_1_t;
/*4002      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER8       temperature;
               INTEGER8       temperature_min;
               INTEGER8       temperature_max;
               }              OD_cell_2_t;

/*******************************************************************************
   TYPE DEFINITIONS FOR OBJECT DICTIONARY INDEXES

   some of those are redundant with CO_SDO.h CO_ObjDicId_t <Common CiA301 object
   dictionary entries>
*******************************************************************************/
/*1000 */
        #define OD_1000_device_type                                 0x1000

/*1001 */
        #define OD_1001_errorRegister                               0x1001

/*1003 */
        #define OD_1003_preDefinedErrorField                        0x1003

        #define OD_1003_0_preDefinedErrorField_maxSubIndex          0
        #define OD_1003_1_preDefinedErrorField_error_1              1
        #define OD_1003_2_preDefinedErrorField_error_2              2
        #define OD_1003_3_preDefinedErrorField_error_3              3
        #define OD_1003_4_preDefinedErrorField_error_4              4
        #define OD_1003_5_preDefinedErrorField_error_5              5
        #define OD_1003_6_preDefinedErrorField_error_6              6
        #define OD_1003_7_preDefinedErrorField_error_7              7
        #define OD_1003_8_preDefinedErrorField_error_8              8

/*1005 */
        #define OD_1005_COB_ID_SYNCMessage                          0x1005

/*1006 */
        #define OD_1006_communication_cycle_period                  0x1006

/*1014 */
        #define OD_1014_cob_id_emergency_message                    0x1014

/*1015 */
        #define OD_1015_inhibitTimeEMCY                             0x1015

/*1016 */
        #define OD_1016_consumerHeartbeatTime                       0x1016

        #define OD_1016_0_consumerHeartbeatTime_maxSubIndex         0
        #define OD_1016_1_consumerHeartbeatTime_consumerHeartbeatTime 1
        #define OD_1016_2_consumerHeartbeatTime_consumerHeartbeatTime 2
        #define OD_1016_3_consumerHeartbeatTime_consumerHeartbeatTime 3
        #define OD_1016_4_consumerHeartbeatTime_consumerHeartbeatTime 4
        #define OD_1016_5_consumerHeartbeatTime_consumerHeartbeatTime 5
        #define OD_1016_6_consumerHeartbeatTime_consumerHeartbeatTime 6
        #define OD_1016_7_consumerHeartbeatTime_consumerHeartbeatTime 7
        #define OD_1016_8_consumerHeartbeatTime_consumerHeartbeatTime 8

/*1017 */
        #define OD_1017_producerHeartbeatTime                       0x1017

/*1018 */
        #define OD_1018_identity                                    0x1018

        #define OD_1018_0_identity_maxSubIndex                      0
        #define OD_1018_1_identity_vendorID                         1
        #define OD_1018_2_identity_productCode                      2
        #define OD_1018_3_identity_revisionNumber                   3
        #define OD_1018_4_identity_serialNumber                     4

/*1019 */
        #define OD_1019_synchronous_counter_overflow_value          0x1019

/*1029 */
        #define OD_1029_errorBehavior                               0x1029

        #define OD_1029_0_errorBehavior_maxSubIndex                 0
        #define OD_1029_1_errorBehavior_communicationError          1
        #define OD_1029_2_errorBehavior_profileOrManufacturerSpecificError 2

/*1200 */
        #define OD_1200_SDOServerParameter                          0x1200

        #define OD_1200_0_SDOServerParameter_maxSubIndex            0
        #define OD_1200_1_SDOServerParameter_COB_IDClientToServer   1
        #define OD_1200_2_SDOServerParameter_COB_IDServerToClient   2
        #define OD_1200_3_SDOServerParameter_node_id_od_sdo_client  3

/*1400 */
        #define OD_1400_RPDOCommunicationParameter                  0x1400

        #define OD_1400_0_RPDOCommunicationParameter_maxSubIndex    0
        #define OD_1400_1_RPDOCommunicationParameter_COB_IDUsedByRPDO 1
        #define OD_1400_2_RPDOCommunicationParameter_transmissionType 2

/*1600 */
        #define OD_1600_RPDOMappingParameter                        0x1600

        #define OD_1600_0_RPDOMappingParameter_maxSubIndex          0
        #define OD_1600_1_RPDOMappingParameter_applicationObject1   1
        #define OD_1600_2_RPDOMappingParameter_applicationObject2   2
        #define OD_1600_3_RPDOMappingParameter_applicationObject3   3
        #define OD_1600_4_RPDOMappingParameter_applicationObject4   4
        #define OD_1600_5_RPDOMappingParameter_applicationObject5   5
        #define OD_1600_6_RPDOMappingParameter_applicationObject6   6
        #define OD_1600_7_RPDOMappingParameter_applicationObject7   7
        #define OD_1600_8_RPDOMappingParameter_applicationObject8   8

/*1800 */
        #define OD_1800_TPDOCommunicationParameter                  0x1800

        #define OD_1800_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1800_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1800_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1800_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1800_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1800_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1800_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1801 */
        #define OD_1801_TPDOCommunicationParameter                  0x1801

        #define OD_1801_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1801_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1801_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1801_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1801_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1801_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1801_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1802 */
        #define OD_1802_TPDOCommunicationParameter                  0x1802

        #define OD_1802_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1802_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1802_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1802_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1802_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1802_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1802_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1803 */
        #define OD_1803_TPDOCommunicationParameter                  0x1803

        #define OD_1803_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1803_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1803_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1803_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1803_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1803_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1803_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1A00 */
        #define OD_1A00_TPDOMappingParameter                        0x1A00

        #define OD_1A00_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A00_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A00_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A00_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A00_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A00_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A00_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A00_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A00_8_TPDOMappingParameter_applicationObject8   8

/*1A01 */
        #define OD_1A01_TPDOMappingParameter                        0x1A01

        #define OD_1A01_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A01_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A01_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A01_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A01_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A01_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A01_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A01_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A01_8_TPDOMappingParameter_applicationObject8   8

/*1A02 */
        #define OD_1A02_TPDOMappingParameter                        0x1A02

        #define OD_1A02_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A02_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A02_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A02_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A02_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A02_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A02_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A02_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A02_8_TPDOMappingParameter_applicationObject8   8

/*1A03 */
        #define OD_1A03_TPDOMappingParameter                        0x1A03

        #define OD_1A03_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A03_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A03_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A03_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A03_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A03_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A03_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A03_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A03_8_TPDOMappingParameter_applicationObject8   8

/*1F80 */
        #define OD_1F80_NMTStartup                                  0x1F80

/*2010 */
        #define OD_2010_scet                                        0x2010

/*2011 */
        #define OD_2011_utc                                         0x2011

/*2100 */
        #define OD_2100_errorStatusBits                             0x2100

/*3000 */
        #define OD_3000_satellite_id                                0x3000

/*3001 */
        #define OD_3001_flight_mode                                 0x3001

/*3002 */
        #define OD_3002_versions                                    0x3002

        #define OD_3002_0_versions_maxSubIndex                      0
        #define OD_3002_1_versions_hw_version                       1
        #define OD_3002_2_versions_configs_version                  2
        #define OD_3002_4_versions_fw_version                       4

/*3003 */
        #define OD_3003_system                                      0x3003

        #define OD_3003_0_system_maxSubIndex                        0
        #define OD_3003_1_system_reset                              1
        #define OD_3003_5_system_uptime                             5
        #define OD_3003_7_system_temperature                        7
        #define OD_3003_8_system_vrefint                            8

/*3009 */
        #define OD_3009_board_id                                    0x3009

/*4000 */
        #define OD_4000_output                                      0x4000

        #define OD_4000_0_output_maxSubIndex                        0
        #define OD_4000_1_output_voltage                            1
        #define OD_4000_2_output_current                            2
        #define OD_4000_3_output_power                              3
        #define OD_4000_4_output_voltage_avg                        4
        #define OD_4000_5_output_current_avg                        5
        #define OD_4000_6_output_power_avg                          6
        #define OD_4000_7_output_voltage_max                        7
        #define OD_4000_8_output_current_max                        8
        #define OD_4000_9_output_power_max                          9
        #define OD_4000_10_output_energy                            10

/*4001 */
        #define OD_4001_cell_1                                      0x4001

        #define OD_4001_0_cell_1_maxSubIndex                        0
        #define OD_4001_1_cell_1_temperature                        1
        #define OD_4001_2_cell_1_temperature_min                    2
        #define OD_4001_3_cell_1_temperature_max                    3

/*4002 */
        #define OD_4002_cell_2                                      0x4002

        #define OD_4002_0_cell_2_maxSubIndex                        0
        #define OD_4002_1_cell_2_temperature                        1
        #define OD_4002_2_cell_2_temperature_min                    2
        #define OD_4002_3_cell_2_temperature_max                    3

/*4003 */
        #define OD_4003_mppt_alg                                    0x4003

/*4004 */
        #define OD_4004_lt1618_iadj                                 0x4004

/*4005 */
        #define OD_4005_time_of_day                                 0x4005

/*******************************************************************************
   STRUCTURES FOR VARIABLES IN DIFFERENT MEMORY LOCATIONS
*******************************************************************************/
#define  CO_OD_FIRST_LAST_WORD     0x55 //Any value from 0x01 to 0xFE. If changed, EEPROM will be reinitialized.

/***** Structure for RAM variables ********************************************/
struct sCO_OD_RAM{
               UNSIGNED32     FirstWord;

/*1000      */ UNSIGNED32     device_type;
/*1001      */ UNSIGNED8      errorRegister;
/*1003      */ UNSIGNED32      preDefinedErrorField[8];
/*1005      */ UNSIGNED32     COB_ID_SYNCMessage;
/*1006      */ UNSIGNED32     communication_cycle_period;
/*1014      */ UNSIGNED32     cob_id_emergency_message;
/*1015      */ UNSIGNED16     inhibitTimeEMCY;
/*1017      */ UNSIGNED16     producerHeartbeatTime;
/*1018      */ OD_identity_t   identity;
/*1019      */ UNSIGNED8      synchronous_counter_overflow_value;
/*1200      */ OD_SDOServerParameter_t SDOServerParameter[1];
/*1800      */ OD_TPDOCommunicationParameter_t TPDOCommunicationParameter[4];
/*1A00      */ OD_TPDOMappingParameter_t TPDOMappingParameter[4];
/*1F80      */ UNSIGNED32     NMTStartup;
/*2010      */ UNSIGNED64     scet;
/*2011      */ UNSIGNED64     utc;
/*2100      */ OCTET_STRING   errorStatusBits[32];
/*3000      */ UNSIGNED8      satellite_id;
/*3001      */ BOOLEAN        flight_mode;
/*3002      */ OD_versions_t   versions;
/*3003      */ OD_system_t     system;
/*3009      */ UNSIGNED8      board_id;
/*4000      */ OD_output_t     output;
/*4001      */ OD_cell_1_t     cell_1;
/*4002      */ OD_cell_2_t     cell_2;
/*4003      */ UNSIGNED8      mppt_alg;
/*4004      */ UNSIGNED16     lt1618_iadj;
/*4005      */ UNSIGNED32     time_of_day;

               UNSIGNED32     LastWord;
};

/***** Structure for ROM variables ********************************************/
struct sCO_OD_ROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for EEPROM variables ********************************************/
struct sCO_OD_EEPROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for PERSIST_COMM variables ********************************************/
struct sCO_OD_PERSIST_COMM{
               UNSIGNED32     FirstWord;

/*1016      */ UNSIGNED32      consumerHeartbeatTime[8];
/*1029      */ UNSIGNED8       errorBehavior[2];
/*1400      */ OD_RPDOCommunicationParameter_t RPDOCommunicationParameter[1];
/*1600      */ OD_RPDOMappingParameter_t RPDOMappingParameter[1];

               UNSIGNED32     LastWord;
};

/***** Declaration of Object Dictionary variables *****************************/
extern struct sCO_OD_RAM CO_OD_RAM;

extern struct sCO_OD_ROM CO_OD_ROM;

extern struct sCO_OD_EEPROM CO_OD_EEPROM;

extern struct sCO_OD_PERSIST_COMM CO_OD_PERSIST_COMM;

/*******************************************************************************
   ALIASES FOR OBJECT DICTIONARY VARIABLES
*******************************************************************************/
/*1000, Data Type: UNSIGNED32 */
        #define OD_device_type_idx                                  0x1000
        #define OD_device_type                                      CO_OD_RAM.device_type

/*1001, Data Type: UNSIGNED8 */
        #define OD_errorRegister_idx                                0x1001
        #define OD_errorRegister                                    CO_OD_RAM.errorRegister

/*1003, Data Type: UNSIGNED32, Array[8] */
        #define OD_preDefinedErrorField_idx                         0x1003
        #define OD_preDefinedErrorField                             CO_OD_RAM.preDefinedErrorField
        #define ODL_preDefinedErrorField_arrayLength                8
        #define ODA_preDefinedErrorField_error_1                    0
        #define ODA_preDefinedErrorField_error_2                    1
        #define ODA_preDefinedErrorField_error_3                    2
        #define ODA_preDefinedErrorField_error_4                    3
        #define ODA_preDefinedErrorField_error_5                    4
        #define ODA_preDefinedErrorField_error_6                    5
        #define ODA_preDefinedErrorField_error_7                    6
        #define ODA_preDefinedErrorField_error_8                    7

/*1005, Data Type: UNSIGNED32 */
        #define OD_COB_ID_SYNCMessage_idx                           0x1005
        #define OD_COB_ID_SYNCMessage                               CO_OD_RAM.COB_ID_SYNCMessage

/*1006, Data Type: UNSIGNED32 */
        #define OD_communication_cycle_period_idx                   0x1006
        #define OD_communication_cycle_period                       CO_OD_RAM.communication_cycle_period

/*1014, Data Type: UNSIGNED32 */
        #define OD_cob_id_emergency_message_idx                     0x1014
        #define OD_cob_id_emergency_message                         CO_OD_RAM.cob_id_emergency_message

/*1015, Data Type: UNSIGNED16 */
        #define OD_inhibitTimeEMCY_idx                              0x1015
        #define OD_inhibitTimeEMCY                                  CO_OD_RAM.inhibitTimeEMCY

/*1016, Data Type: UNSIGNED32, Array[8] */
        #define OD_consumerHeartbeatTime_idx                        0x1016
        #define OD_consumerHeartbeatTime                            CO_OD_PERSIST_COMM.consumerHeartbeatTime
        #define ODL_consumerHeartbeatTime_arrayLength               8
        #define ODA_consumerHeartbeatTime_consumerHeartbeatTime     0

/*1017, Data Type: UNSIGNED16 */
        #define OD_producerHeartbeatTime_idx                        0x1017
        #define OD_producerHeartbeatTime                            CO_OD_RAM.producerHeartbeatTime

/*1018, Data Type: identity_t */
        #define OD_identity_idx                                     0x1018
        #define OD_identity                                         CO_OD_RAM.identity

/*1019, Data Type: UNSIGNED8 */
        #define OD_synchronous_counter_overflow_value_idx           0x1019
        #define OD_synchronous_counter_overflow_value               CO_OD_RAM.synchronous_counter_overflow_value

/*1029, Data Type: UNSIGNED8, Array[2] */
        #define OD_errorBehavior_idx                                0x1029
        #define OD_errorBehavior                                    CO_OD_PERSIST_COMM.errorBehavior
        #define ODL_errorBehavior_arrayLength                       2
        #define ODA_errorBehavior_communicationError                0
        #define ODA_errorBehavior_profileOrManufacturerSpecificError 1

/*1200, Data Type: SDOServerParameter_t */
        #define OD_SDOServerParameter_idx                           0x1200
        #define OD_SDOServerParameter                               CO_OD_RAM.SDOServerParameter

/*1400, Data Type: RPDOCommunicationParameter_t */
        #define OD_RPDOCommunicationParameter_idx                   0x1400
        #define OD_RPDOCommunicationParameter                       CO_OD_PERSIST_COMM.RPDOCommunicationParameter

/*1600, Data Type: RPDOMappingParameter_t */
        #define OD_RPDOMappingParameter_idx                         0x1600
        #define OD_RPDOMappingParameter                             CO_OD_PERSIST_COMM.RPDOMappingParameter

/*1800, Data Type: TPDOCommunicationParameter_t */
        #define OD_TPDOCommunicationParameter_idx                   0x1800
        #define OD_TPDOCommunicationParameter                       CO_OD_RAM.TPDOCommunicationParameter

/*1A00, Data Type: TPDOMappingParameter_t */
        #define OD_TPDOMappingParameter_idx                         0x1A00
        #define OD_TPDOMappingParameter                             CO_OD_RAM.TPDOMappingParameter

/*1F80, Data Type: UNSIGNED32 */
        #define OD_NMTStartup_idx                                   0x1F80
        #define OD_NMTStartup                                       CO_OD_RAM.NMTStartup

/*2010, Data Type: UNSIGNED64 */
        #define OD_scet_idx                                         0x2010
        #define OD_scet                                             CO_OD_RAM.scet

/*2011, Data Type: UNSIGNED64 */
        #define OD_utc_idx                                          0x2011
        #define OD_utc                                              CO_OD_RAM.utc

/*2100, Data Type: OCTET_STRING */
        #define OD_errorStatusBits_idx                              0x2100
        #define OD_errorStatusBits                                  CO_OD_RAM.errorStatusBits
        #define ODL_errorStatusBits_stringLength                    32

/*3000, Data Type: UNSIGNED8 */
        #define OD_satellite_id_idx                                 0x3000
        #define OD_satellite_id                                     CO_OD_RAM.satellite_id

/*3001, Data Type: BOOLEAN */
        #define OD_flight_mode_idx                                  0x3001
        #define OD_flight_mode                                      CO_OD_RAM.flight_mode

/*3002, Data Type: versions_t */
        #define OD_versions_idx                                     0x3002
        #define OD_versions                                         CO_OD_RAM.versions

/*3003, Data Type: system_t */
        #define OD_system_idx                                       0x3003
        #define OD_system                                           CO_OD_RAM.system

/*3009, Data Type: UNSIGNED8 */
        #define OD_board_id_idx                                     0x3009
        #define OD_board_id                                         CO_OD_RAM.board_id

/*4000, Data Type: output_t */
        #define OD_output_idx                                       0x4000
        #define OD_output                                           CO_OD_RAM.output

/*4001, Data Type: cell_1_t */
        #define OD_cell_1_idx                                       0x4001
        #define OD_cell_1                                           CO_OD_RAM.cell_1

/*4002, Data Type: cell_2_t */
        #define OD_cell_2_idx                                       0x4002
        #define OD_cell_2                                           CO_OD_RAM.cell_2

/*4003, Data Type: UNSIGNED8 */
        #define OD_mppt_alg_idx                                     0x4003
        #define OD_mppt_alg                                         CO_OD_RAM.mppt_alg

/*4004, Data Type: UNSIGNED16 */
        #define OD_lt1618_iadj_idx                                  0x4004
        #define OD_lt1618_iadj                                      CO_OD_RAM.lt1618_iadj

/*4005, Data Type: UNSIGNED32 */
        #define OD_time_of_day_idx                                  0x4005
        #define OD_time_of_day                                      CO_OD_RAM.time_of_day

#endif
// clang-format on
